---
# file: bind/tasks/main.yml
#
# tasks file
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- include: installation.yml
  tags: installation
  sudo: yes

- include: configuration.yml
  tags: configuration
  sudo: yes
